-- Types

-- Tables
DROP TABLE IF EXISTS UserVotesAnswer;
CREATE TABLE UserVotesAnswer(
    userId INTEGER NOT NULL REFERENCES user(id) ON UPDATE CASCADE,
    answerId INTEGER NOT NULL REFERENCES answer(id) ON UPDATE CASCADE,
    PRIMARY KEY (userId,answerId)
);

DROP TABLE IF EXISTS ReportAnswer;
CREATE TABLE ReportAnswer(
    userId INTEGER NOT NULL REFERENCES user(id) ON UPDATE CASCADE,
    answerId INTEGER NOT NULL REFERENCES answer(id) ON UPDATE CASCADE,
    PRIMARY KEY (userId,answerId)
);

DROP TABLE IF EXISTS Question;
CREATE TABLE Question(
    questionId SERIAL PRIMARY KEY,
    questionOwnerId INTEGER NOT NULL REFERENCES user(id) ON UPDATE CASCADE,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    "date" TIMESTAMP WITH TIME zone DEFAULT now() NOT NULL
);

DROP TABLE IF EXISTS UserVotesQuestion;
CREATE TABLE UserVotesQuestion(
    userId INTEGER NOT NULL REFERENCES user(id) ON UPDATE CASCADE,
    questionId INTEGER NOT NULL REFERENCES question(id) ON UPDATE CASCADE,
    PRIMARY KEY (userId,questionId)
);

DROP TABLE IF EXISTS ReportQuestion;
CREATE TABLE ReportQuestion(
    userId INTEGER NOT NULL REFERENCES user(id) ON UPDATE CASCADE,
    questionId INTEGER NOT NULL REFERENCES question(id) ON UPDATE CASCADE,
    PRIMARY KEY (userId,questionId)
);
